# Generated by Django 3.0.8 on 2020-07-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_quermiprofileuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(choices=[('ES', 'Spanish'), ('EN', 'English')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(choices=[('HCR', 'Home caring'), ('MOR', 'Market orders'), ('WKR', 'Walk around'), ('PRO', 'Procedures'), ('PHY', 'Pharmacy'), ('HCL', 'Home cleaning'), ('SFC', 'Self caring'), ('OTH', 'Other')], unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='quermiprofileuser',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='quermiprofileuser',
            name='languages',
        ),
        migrations.AlterField(
            model_name='quermiprofileuser',
            name='role',
            field=models.TextField(choices=[('PATIENT', 'Patient'), ('CARE_PROVIDER', 'Care Provider')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='quermiprofileuser',
            name='services',
        ),
        migrations.AddField(
            model_name='quermiprofileuser',
            name='languages',
            field=models.ManyToManyField(to='users.ProfileLanguage'),
        ),
        migrations.AddField(
            model_name='quermiprofileuser',
            name='services',
            field=models.ManyToManyField(to='users.ProfileServices'),
        ),
    ]
