# Generated by Django 3.0.8 on 2020-08-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_extend_limit_max_length_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quermiprofileuser',
            name='doc_id_photo_url',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quermiprofileuser',
            name='profile_photo_url',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
