# Generated by Django 3.1 on 2020-08-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_image_url_fields_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quermiprofileuser',
            name='profile_status',
            field=models.JSONField(default=dict, max_length=100),
        ),
    ]
