# Generated by Django 3.1 on 2020-09-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_include_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quermiprofileuser',
            name='profile_photo_url',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
