# Generated by Django 3.1 on 2020-09-06 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_increase_max_length_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quermiprofileuser',
            name='rate',
        ),
    ]
