# Generated by Django 3.1 on 2020-11-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rate_field_property_on_profile_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='quermiprofileuser',
            name='customer_payment_id',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
