# Generated by Django 3.1 on 2020-12-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_quermiprofileuser_customer_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quermiprofileuser',
            name='verified_profile',
            field=models.BooleanField(default=False),
        ),
    ]
