# Generated by Django 3.1 on 2020-12-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_verified_field_on_profile_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quermiprofileuser',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
