# Generated by Django 3.1 on 2020-09-11 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rate_field_property_on_profile_model'),
        ('services', '0003_add_migration_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='care_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_person', to='users.quermiprofileuser'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='users.quermiprofileuser'),
        ),
        migrations.AlterField(
            model_name='report',
            name='origin_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_profile', to='users.quermiprofileuser'),
        ),
        migrations.AlterField(
            model_name='report',
            name='profile_rated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_rated', to='users.quermiprofileuser'),
        ),
    ]
