# Generated by Django 3.1 on 2020-09-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_replace_user_to_profile_as_model_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.TextField(choices=[('CPEN', 'Pending contact'), ('CADD', 'Contact added'), ('CACT', 'Actived contract'), ('CDFT', 'Defeated contract')]),
        ),
    ]
