# Generated by Django 3.1 on 2020-11-30 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_quermiprofileuser_customer_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.TextField(unique=True)),
                ('last_four_digits_card', models.TextField(max_length=4)),
                ('exp_month', models.TextField()),
                ('exp_year', models.TextField()),
                ('card_type', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to='users.quermiprofileuser')),
            ],
        ),
    ]
