# Generated by Django 3.1 on 2020-12-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField(max_length=512)),
                ('price', models.IntegerField()),
                ('mode', models.TextField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')])),
            ],
        ),
    ]
