# Generated by Django 3.1 on 2020-12-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscriptionmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmode',
            name='description',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
