# Generated by Django 3.1 on 2020-12-07 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20201206_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentregister',
            old_name='token_id',
            new_name='payment_id',
        ),
    ]
