# Generated by Django 3.1 on 2020-12-07 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_quermiprofileuser_customer_payment_id'),
        ('payments', '0004_auto_20201207_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_payment_id', models.TextField(unique=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.quermiprofileuser')),
            ],
        ),
    ]
